name: Playwright

on: pull_request

jobs:
  e2e:
    name: E2E tests
    runs-on: macos-latest # or ubuntu-latest, windows-latest
    steps:
      - name: waiting for 200 from the Vercel preview
        uses: patrickedqvist/wait-for-vercel-preview@master
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      - name: run tests
        run: echo 'test'
        env:
          BASEURL: ${{steps.waitFor200.outputs.url}}
