name: Playwright-Home

on: pull_request

jobs:
  e2e:
    name: E2E tests
    runs-on: macos-latest # or ubuntu-latest, windows-latest
    steps:
      - name: waiting for 200 from the Vercel preview
        uses: yanawaro/wait-for-vercel-preview@multiple-deploys
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 120
          projects: '["nextjs-multi-zone", "nextjs-multi-zone-2"]'
      - name: run tests
        run: echo ${{steps.waitFor200.outputs.urls}}

        # env:
        #   BASEURL: ${{steps.waitFor200.outputs.url}}
